source ~/.config/tmux/palettes/catppuccin-mocha-scheme.conf

# Remapping prefix
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Set default shell
set -g default-shell /usr/bin/fish

# Enable flexible window switching
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

# Enable activity monitoring
set -g monitor-bell on

# Enable color support
set -g default-terminal 'tmux-256color'
set -g terminal-overrides ',*:RGB'

# Modify status bar
set -g status-style 'fg=#{@FG},bg=#{@BG},bold'
set -g status-left ''
set -g status-right-style 'fg=#{@IGNORED},bg=#{@BG}'
set -g status-right '#{?client_prefix,#[bg=#{@BG2}#,fg=#{@FG}] CMD #[default],} #[bg=#{@BG2}] #S '

# Modify window status
set -g window-status-bell-style ''  # Needed so that the colors aren't reversed
color="#{?window_bell_flag,#{@BRIGHTERROR},#{@BG1}}"
color2="#{?window_bell_flag,#{@ERROR},#{@BG2}}"
fg_color="#{?window_bell_flag,#{@BG},#{@IGNORED}}"
set -g window-status-format "#[fg=${fg_color}]#[bg=${color}] #I #[bg=${color2}] #W #F "
set -g window-status-current-format "#[bg=#{@BG1}] #I #[bg=#{@BG2}] #W "

# Pane border style
set -g pane-border-style 'fg=#{@OUTLINE},bg=default'
set -g pane-active-border-style 'fg=#{@RED},bg=default'
set -g pane-border-lines single

# Message line (Command prefix + :)
set -g message-style 'fg=default,bg=default'

# Popup menu
set -g menu-style 'bg=default,fg=default'
set -g menu-selected-style 'bg=#{@HOVER},fg=default'
set -g menu-border-style 'fg=#{@FG},bg=default'

# Keybindings
# Reload configurations
bind r source-file ~/.config/tmux/tmux.conf
# Switch panes
bind -n M-C-k select-pane -U 
bind -n M-C-j select-pane -D 
bind -n M-C-h select-pane -L 
bind -n M-C-l select-pane -R 
# Resize panes
bind -r C-k resize-pane -U 3
bind -r C-j resize-pane -D 3
bind -r C-h resize-pane -L 3 
bind -r C-l resize-pane -R 3 
bind -r K resize-pane -U 1
bind -r J resize-pane -D 1
bind -r H resize-pane -L 1
bind -r L resize-pane -R 1
# Move window orders
bind -r M-l swapw -t +1 \; next-window
bind -r M-h swapw -t -1 \; previous-window

### TPM (Termux Plugin Manager)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Put the plugins you want to install in here
# tmux-yank
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
