# base
rootcolor=0x24273aff
# surface1
bordercolor=0x494d64ff
# lavender
focuscolor=0xb7bdf8ff
# green
maximizescreencolor=0xa6da95ff
# red
urgentcolor=0xed8796ff
# yellow
scratchpadcolor=0xeed49fff

# Uses default colors
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff
