# base
rootcolor=0x1e1e2eff
# surface1
bordercolor=0x45475aff
# lavender
focuscolor=0xb4befeff
# green
maximizescreencolor=0xa6e3a1ff
# red
urgentcolor=0xf38ba8ff
# yellow
scratchpadcolor=0xf9e2afff

# Uses default colors
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff
