###	APPEARANCE
# border
borderpx=2
border_radius=10

# gaps
gappih=5
gappiv=5
gappoh=10
gappov=10

# cursor
cursor_theme=Bibata-Modern-Classic
cursor_size=20
env=XCURSOR_THEME,Bibata-Modern-Classic
env=XCURSOR_SIZE,20

# animations
animation_type_open=slide
animation_type_close=zoom
animation_duration_focus=300
animation_duration_move=500
animation_duration_open=500
animation_duration_close=500
animation_duration_tag=300
animation_curve_tag=0.87,0,0.13,1
animation_curve_open=0.16,1,0.3,1
animation_curve_close=0.16,1,0.3,1
animation_curve_focus=0.11,0,0.5,0

blur=0

source=~/.config/mango/themes/catppuccin-macchiato.conf
