# vi: ft=tmux

set -g @ROSEWATER '#f5e0dc'
set -g @FLAMINGO '#f2cdcd'
set -g @PINK '#f5c2e7'
set -g @MAUVE '#cba6f7'
set -g @RED '#f38ba8'
set -g @MAROON '#eba0ac'
set -g @PEACH '#fab387'
set -g @YELLOW '#f9e2af'
set -g @GREEN '#a6e3a1'
set -g @TEAL '#94e2d5'
set -g @SKY '#89dceb'
set -g @SAPPHIRE '#74c7ec'
set -g @BLUE '#89b4fa'
set -g @LAVENDER '#b4befe'
set -g @TEXT '#cdd6f4'
set -g @SUBTEXT1 '#bac2de'
set -g @SUBTEXT0 '#a6adc8'
set -g @OVERLAY2 '#9399b2'
set -g @OVERLAY1 '#7f849c'
set -g @OVERLAY0 '#6c7086'
set -g @SURFACE2 '#585b70'
set -g @SURFACE1 '#45475a'
set -g @SURFACE0 '#313244'
set -g @BASE '#1e1e2e'
set -g @MANTLE '#181825'
set -g @CRUST '#11111b'
