source ~/.config/tmux/palettes/catppuccin-macchiato.conf

# Using all caps so it's easier to understand user defined variables
set -gF @BG "#{@BASE}"
set -gF @BG1 "#{@MANTLE}"
set -gF @BG2 "#{@CRUST}"
set -gF @FG "#{@TEXT}"
set -gF @FG1 "#{@SUBTEXT1}"
set -gF @FG2 "#{@SUBTEXT0}"
set -gF @MODERATE "#{@YELLOW}"
set -gF @BRIGHTMODERATE "#{@ROSEWATER}"
set -gF @WARNING "#{@PEACH}"
set -gF @SUCCESS "#{@GREEN}"
set -gF @ERROR "#{@RED}"
set -gF @BRIGHTERROR "#{@MAROON}"
set -gF @INFO "#{@BLUE}"
set -gF @IGNORED "#{@OVERLAY0}"
set -gF @HOVER "#{@SURFACE0}"
set -gF @OUTLINE "#{@SURFACE1}"

# Alt colors
set -gF @PINK "#{@PINK}"
set -gF @TEAL "#{@TEAL}"
set -gF @MAUVE "#{@MAUVE}"

# vi: ft=tmux
