# vi: ft=tmux

set -g @BG_DIM "#1B1B1B"
set -g @BG0 "#282828"
set -g @BG1 "#32302F"
set -g @BG2 "#32302F"
set -g @BG3 "#45403D"
set -g @BG4 "#45403D"
set -g @BG5 "#5A524C"

set -g @BG_DIFF_RED "#402120"
set -g @BG_DIFF_GREEN "#34381B"
set -g @BG_DIFF_BLUE "#0E363E"
set -g @BG_STATUSLINE1 "#32302F"
set -g @BG_STATUSLINE2 "#3A3735"
set -g @BG_STATUSLINE3 "#504945"
set -g @BG_CURRENT_WORD "#3C3836"

set -g @BG_VISUAL_RED "#4C3432"
set -g @BG_VISUAL_GREEN "#3B4439"
set -g @BG_VISUAL_BLUE "#374141"
set -g @BG_VISUAL_YELLOW "#4F422E"
set -g @BG_VISUAL_PURPLE "#443840"

set -g @FG0 "#D4BE98"
set -g @FG1 "#DDC7A1"

set -g @RED "#EA6962"
set -g @GREEN "#A9B665"
set -g @BLUE "#7DAEA3"
set -g @YELLOW "#D8A657"
set -g @PURPLE "#D3869B"
set -g @ORANGE "#E78A4E"
set -g @AQUA "#89B482"

set -g @BG_RED "#EA6962"
set -g @BG_GREEN "#A9B665"
set -g @BG_YELLOW "#D8A657"

set -g @GREY0 "#7C6F64"
set -g @GREY1 "#928374"
set -g @GREY2 "#A89984"
