source ~/.config/tmux/palettes/gruvbox-material-dark.conf

# Using all caps so it's easier to understand user defined variables
set -gF @BG "#{@BG0}"
set -gF @BG1 "#{@BG_DIM}"
set -gF @BG2 "#{@BG1}"
set -gF @FG "#{@FG0}"
set -gF @FG1 "#{@FG1}"
set -gF @FG2 "#{@FG1}"
set -gF @MODERATE "#{@YELLOW}"
set -gF @BRIGHTMODERATE "#{@YELLOW}"
set -gF @WARNING "#{@ORANGE}"
set -gF @SUCCESS "#{@GREEN}"
set -gF @ERROR "#{@RED}"
set -gF @BRIGHTERROR "#{@RED}"
set -gF @INFO "#{@BLUE}"
set -gF @IGNORED "#{@GREY0}"
set -gF @HOVER "#{@BG5}"
set -gF @OUTLINE "#{@GREY0}"

# Alt colors
set -gF @PINK "#{@PURPLE}"
set -gF @TEAL "#{@AQUA}"
set -gF @MAUVE "#{@PURPLE}"

# vi: ft=tmux
