source ~/.config/tmux/palettes/onedark.conf

# Using all caps so it's easier to understand user defined variables
set -gF @BG "#{@BG0}"
set -gF @BG1 "#{@BG1}"
set -gF @BG2 "#{@BG2}"
set -gF @FG "#{@FG}"
set -gF @FG1 "#{@GREY}"
set -gF @FG2 "#{@GREY}"
set -gF @MODERATE "#{@YELLOW}"
set -gF @BRIGHTMODERATE "#{@YELLOW}"
set -gF @WARNING "#{@ORANGE}"
set -gF @SUCCESS "#{@GREEN}"
set -gF @ERROR "#{@RED}"
set -gF @BRIGHTERROR "#{@RED}"
set -gF @INFO "#{@BLUE}"
set -gF @IGNORED "#{@GREY}"
set -gF @HOVER "#{@BG2}"
set -gF @OUTLINE "#{@GREY}"

# Alt colors
set -gF @PINK "#{@PURPLE}"
set -gF @TEAL "#{@CYAN}"
set -gF @MAUVE "#{@PURPLE}"

# vi: ft=tmux
