# vi: ft=tmux
set -g @BLACK "#181a1f"
set -g @BG0 "#282c34"
set -g @BG1 "#31353f"
set -g @BG2 "#393f4a"
set -g @BG3 "#3b3f4c"
set -g @BG_D "#21252b"
set -g @BG_BLUE "#73b8f1"
set -g @BG_YELLOW "#ebd09c"
set -g @FG "#abb2bf"
set -g @PURPLE "#c678dd"
set -g @GREEN "#98c379"
set -g @ORANGE "#d19a66"
set -g @BLUE "#61afef"
set -g @YELLOW "#e5c07b"
set -g @CYAN "#56b6c2"
set -g @RED "#e86671"
set -g @GREY "#5c6370"
set -g @LIGHT_GREY "#848b98"
set -g @DARK_CYAN "#2b6f77"
set -g @DARK_RED "#993939"
set -g @DARK_YELLOW "#93691d"
set -g @DARK_PURPLE "#8a3fa0"
set -g @DIFF_ADD "#31392b"
set -g @DIFF_DELETE "#382b2c"
set -g @DIFF_CHANGE "#1c3448"
set -g @DIFF_TEXT "#2c5372"
